# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
before:
  hooks: []
builds:
  - id: PPPwn
    main: main.go
    binary: PPPwn
    env:
      - CGO_ENABLED=1
    flags:
      - -trimpath
    goos:
      - linux
#      - windows
#      - darwin
    goarch:
#      - 386
      - amd64
#      - arm
#      - arm64
#      - mips
#      - mipsle
#      - mips64
#      - mips64le
#    goarm:
#      - 6
#      - 7
#    gomips:
#      - hardfloat
#      - softfloat
#    ignore:
#      - goos: windows
#        goarch: arm
#        goarm: 6
#      - goos: windows
#        goarch: arm
#        goarm: 7
    ldflags:
      - -s -w

archives:
  - name_template: >-
      {{- .ProjectName }}_
      {{- .Tag }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
      {{- if .Mips }}_{{ .Mips }}{{ end }}
    allow_different_binary_count: true
    builds:
      - PPPwn
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
release:
  prerelease: auto
