interface: \Device\NPF_{00000000-0000-0000-0000-000000000000}

injects:
    - target_mac: 41:41:41:41:41:41
      firmware: 950
      stage1_file: testdata/stage1/stage1.bin
      stage2F_file: testdata/stage2/stage2.bin

server:
    host: ""
    port: 8899
debug: true